runtime: python39
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: index.app

libraries:
- name: Bio
  version: 1.4.0
- name: bokeh
  version: 2.4.3
- name: Flask
  version: 2.2.2
- name: pandas
  version: 1.4.2
- name: tornado
  version: 6.1