environment: 'heroku'

app:
  bokeh:
    path: "$PATH"
  flask:
    path: "/"

proxy:
  bokeh:
    local:
      address: "127.0.0.1"
      port: "$PORT"
      path: "$PATH/ws"
  flask:
    local:
      address: "127.0.0.1"
      port: 8000
      path: "/"
    heroku:
      domain: "strand-test.herokuapp.com"
      address: "0.0.0.0"
      port: "$PORT"
      path: "/"

cdn:
  bokeh:
    url: "https://cdn.bokeh.org/bokeh/release"
